version: '3.1'
services:

  stats-server:
    build: ./ewm-stat-service/stat_service

    image:
      stat_server:latest
    container_name: stat_server

    ports:
      - "9090:9090"
      - "9091:9091"

    depends_on:
      - stats_service-db
    environment:
    - URL_DB=jdbc:postgresql://stats_service-db:5432/stat_db
    - USERNAME_DB=asd
    - PASSWORD_DB=123


  stats_service-db:
    image: postgres:14-alpine
    container_name: state_server-db
    ports:
    - "6062:5432"
    environment:
    - POSTGRES_DB=stat_db
    - POSTGRES_USER=asd
    - POSTGRES_PASSWORD=123



  ewm-service:
    build: ./ewm-main-service
    image:
     ewm-service:latest
    container_name: ewm-service

    ports:
     - "8080:8080"

    depends_on:
     - ewm-db
    environment:
      - SERVICE_URL=jdbc:postgresql://ewm-db:6464/ewm_db
#      - SERVICE_USERNAME=postgres
#      - SERVICE_PASSWORD=123

  ewm-db:
    image: postgres:14
    container_name: postgres-main-db
    ports:
     - "6464:5432"
    environment:
        POSTGRES_HOST_AUTH_METHOD: "trust"
#      - EWM_DB=ewm_db
#      - EWM_USER=postgres
#      - EWM_PASSWORD=123