version: '3.1'
services:
  stats-server:
    build: ./stats-server/stat_service
    image:
      stat_server:latest
    container_name: stat_server

    ports:
      - "9090:9090"
      - "9091:9091"

    depends_on:
      - stats-db
    environment:
          - URL_DB=postgresql://db:1111/java-explore-with-me/state/sta_service
          - USERNAME_DB=postgres
          - PASSWORD_DB=123
  stats-db:
      image: postgres:14-alpine
      volumes:
        - /var/lib/postgresql/data/
      container_name: state_server-db
      ports:
        - "1111:1111"
      environment:
        - POSTGRES_DB=java-explore-with-me
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=123
#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
